#!/bin/sh
cd ..
python detect_ae_NSL.py --attack 'fgsm' --iter_n 1
python detect_ae_NSL.py --attack 'fgsm' --iter_n 2
python detect_ae_NSL.py --attack 'fgsm' --iter_n 3
python detect_ae_NSL.py --attack 'fgsm' --iter_n 4
python detect_ae_NSL.py --attack 'fgsm' --iter_n 5
python detect_ae_NSL.py --attack 'fgsm' --iter_n 6
python detect_ae_NSL.py --attack 'fgsm' --iter_n 7
python detect_ae_NSL.py --attack 'fgsm' --iter_n 8
python detect_ae_NSL.py --attack 'fgsm' --iter_n 9
python detect_ae_NSL.py --attack 'fgsm' --iter_n 10
python detect_ae_NSL.py --attack 'fgsm' --iter_n 11
python detect_ae_NSL.py --attack 'fgsm' --iter_n 12
python detect_ae_NSL.py --attack 'fgsm' --iter_n 13
python detect_ae_NSL.py --attack 'fgsm' --iter_n 14
python detect_ae_NSL.py --attack 'fgsm' --iter_n 15
python detect_ae_NSL.py --attack 'fgsm' --iter_n 16
python detect_ae_NSL.py --attack 'fgsm' --iter_n 17
python detect_ae_NSL.py --attack 'fgsm' --iter_n 18
python detect_ae_NSL.py --attack 'fgsm' --iter_n 19
python detect_ae_NSL.py --attack 'fgsm' --iter_n 20
python detect_ae_NSL.py --attack 'fgsm' --iter_n 21
python detect_ae_NSL.py --attack 'fgsm' --iter_n 22
python detect_ae_NSL.py --attack 'fgsm' --iter_n 23
python detect_ae_NSL.py --attack 'fgsm' --iter_n 24
python detect_ae_NSL.py --attack 'fgsm' --iter_n 25
python detect_ae_NSL.py --attack 'fgsm' --iter_n 26
python detect_ae_NSL.py --attack 'fgsm' --iter_n 27
python detect_ae_NSL.py --attack 'fgsm' --iter_n 28
python detect_ae_NSL.py --attack 'fgsm' --iter_n 29
python detect_ae_NSL.py --attack 'fgsm' --iter_n 30
python detect_ae_NSL.py --attack 'fgsm' --iter_n 31

python detect_ae_NSL.py --attack 'bim' --iter_n 1
python detect_ae_NSL.py --attack 'bim' --iter_n 2
python detect_ae_NSL.py --attack 'bim' --iter_n 3
python detect_ae_NSL.py --attack 'bim' --iter_n 4
python detect_ae_NSL.py --attack 'bim' --iter_n 5
python detect_ae_NSL.py --attack 'bim' --iter_n 6
python detect_ae_NSL.py --attack 'bim' --iter_n 7
python detect_ae_NSL.py --attack 'bim' --iter_n 8
python detect_ae_NSL.py --attack 'bim' --iter_n 9
python detect_ae_NSL.py --attack 'bim' --iter_n 10
python detect_ae_NSL.py --attack 'bim' --iter_n 11
python detect_ae_NSL.py --attack 'bim' --iter_n 12
python detect_ae_NSL.py --attack 'bim' --iter_n 13
python detect_ae_NSL.py --attack 'bim' --iter_n 14
python detect_ae_NSL.py --attack 'bim' --iter_n 15
python detect_ae_NSL.py --attack 'bim' --iter_n 16
python detect_ae_NSL.py --attack 'bim' --iter_n 17
python detect_ae_NSL.py --attack 'bim' --iter_n 18
python detect_ae_NSL.py --attack 'bim' --iter_n 19
python detect_ae_NSL.py --attack 'bim' --iter_n 20
python detect_ae_NSL.py --attack 'bim' --iter_n 21
python detect_ae_NSL.py --attack 'bim' --iter_n 22
python detect_ae_NSL.py --attack 'bim' --iter_n 23
python detect_ae_NSL.py --attack 'bim' --iter_n 24
python detect_ae_NSL.py --attack 'bim' --iter_n 25
python detect_ae_NSL.py --attack 'bim' --iter_n 26
python detect_ae_NSL.py --attack 'bim' --iter_n 27
python detect_ae_NSL.py --attack 'bim' --iter_n 28
python detect_ae_NSL.py --attack 'bim' --iter_n 29
python detect_ae_NSL.py --attack 'bim' --iter_n 30
python detect_ae_NSL.py --attack 'bim' --iter_n 31



python detect_ae_NSL.py --attack 'cw' --iter_n 1